### PR TITLE
feat: Accept custom headers and add add X-Client-Info header

### PR DESCRIPTION
**Pull request by dshukertjr**
We decided that we actually want to have separate `X-Client-Info` header for supabase_flutter, so adding that one as well.

### CODE REVIEW

**Comment by Vinzent03** [comment]
I think for #179 it's better suited to pass custom headers at each rpc call, doesn't it?

**Comment by Vinzent03** [comment]
So adding custom headers to the constructor is a nice side effect of this change, right?

**Comment by dshukertjr** [comment]
Yeah, why not? JS SDK and all other SDKs allows for custom header to be set, so I think we can leave it!

**Review by Vinzent03 — APPROVED** [review]
Sure, just wanted to clarify.

**Pull request merged**
